DROP TABLE IF EXISTS T_OC_PLANO_COBERTURA;
DROP TABLE IF EXISTS T_OC_SIMULACAO;
DROP TABLE IF EXISTS T_OC_CAMPANHA_REGIAO;
DROP TABLE IF EXISTS T_OC_CAMPANHA;
DROP TABLE IF EXISTS T_OC_REGIAO;
DROP TABLE IF EXISTS T_OC_CANAL;
DROP TABLE IF EXISTS T_OC_CLIENTE;

CREATE TABLE T_OC_CLIENTE (
    id_cliente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    documento VARCHAR(30) UNIQUE,
    email VARCHAR(120) NOT NULL,
    telefone VARCHAR(30),
    segmento VARCHAR(80) NOT NULL,
    data_cadastro TIMESTAMP NOT NULL,
    ativo BOOLEAN NOT NULL
);

CREATE TABLE T_OC_CANAL (
    id_canal BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    nome VARCHAR(120) NOT NULL,
    tipo_conteudo VARCHAR(80) NOT NULL,
    publico_alvo VARCHAR(120) NOT NULL,
    classificacao_indicativa VARCHAR(20),
    ativo BOOLEAN NOT NULL,
    CONSTRAINT fk_canais_clientes FOREIGN KEY (id_cliente) REFERENCES T_OC_CLIENTE(id_cliente)
);

CREATE TABLE T_OC_REGIAO (
    id_regiao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    pais VARCHAR(80) NOT NULL,
    populacao_estimada INTEGER NOT NULL CHECK (populacao_estimada >= 0),
    indice_conectividade DECIMAL(5,2) NOT NULL CHECK (indice_conectividade BETWEEN 0 AND 100),
    latitude DECIMAL(10,6),
    longitude DECIMAL(10,6),
    area_km2 DECIMAL(12,2) NOT NULL CHECK (area_km2 > 0),
    prioridade_social INTEGER NOT NULL CHECK (prioridade_social BETWEEN 1 AND 5)
);

CREATE TABLE T_OC_CAMPANHA (
    id_campanha BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente BIGINT NOT NULL,
    id_canal BIGINT NOT NULL,
    nome VARCHAR(140) NOT NULL,
    descricao VARCHAR(500),
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    duracao_horas INTEGER NOT NULL CHECK (duracao_horas > 0),
    qualidade_desejada VARCHAR(20) NOT NULL CHECK (qualidade_desejada IN ('SD', 'HD', 'FULL_HD', '4K')),
    orcamento DECIMAL(14,2) NOT NULL CHECK (orcamento >= 0),
    status VARCHAR(30) NOT NULL CHECK (status IN ('PLANEJADA', 'EM_ANALISE', 'APROVADA', 'CANCELADA', 'FINALIZADA')),
    CONSTRAINT fk_campanhas_clientes FOREIGN KEY (id_cliente) REFERENCES T_OC_CLIENTE(id_cliente),
    CONSTRAINT fk_campanhas_canais FOREIGN KEY (id_canal) REFERENCES T_OC_CANAL(id_canal),
    CONSTRAINT ck_campanhas_periodo CHECK (data_inicio <= data_fim)
);

CREATE TABLE T_OC_CAMPANHA_REGIAO (
    id_campanha BIGINT NOT NULL,
    id_regiao BIGINT NOT NULL,
    prioridade INTEGER NOT NULL CHECK (prioridade BETWEEN 1 AND 5),
    observacao VARCHAR(300),
    PRIMARY KEY (id_campanha, id_regiao),
    CONSTRAINT fk_cr_campanhas FOREIGN KEY (id_campanha) REFERENCES T_OC_CAMPANHA(id_campanha) ON DELETE CASCADE,
    CONSTRAINT fk_cr_regioes FOREIGN KEY (id_regiao) REFERENCES T_OC_REGIAO(id_regiao)
);

CREATE TABLE T_OC_SIMULACAO (
    id_simulacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_campanha BIGINT NOT NULL,
    custo_estimado DECIMAL(14,2) NOT NULL CHECK (custo_estimado >= 0),
    alcance_estimado INTEGER NOT NULL CHECK (alcance_estimado >= 0),
    qualidade_sinal DECIMAL(5,2) NOT NULL CHECK (qualidade_sinal BETWEEN 0 AND 100),
    viabilidade VARCHAR(20) NOT NULL CHECK (viabilidade IN ('BAIXA', 'MEDIA', 'ALTA')),
    recomendacao VARCHAR(600) NOT NULL,
    data_simulacao TIMESTAMP NOT NULL,
    CONSTRAINT fk_simulacoes_campanhas FOREIGN KEY (id_campanha) REFERENCES T_OC_CAMPANHA(id_campanha) ON DELETE CASCADE
);

CREATE TABLE T_OC_PLANO_COBERTURA (
    id_plano BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_campanha BIGINT NOT NULL,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    custo_total DECIMAL(14,2) NOT NULL CHECK (custo_total >= 0),
    alcance_total INTEGER NOT NULL CHECK (alcance_total >= 0),
    viabilidade_geral VARCHAR(20) NOT NULL CHECK (viabilidade_geral IN ('BAIXA', 'MEDIA', 'ALTA')),
    CONSTRAINT fk_planos_campanhas FOREIGN KEY (id_campanha) REFERENCES T_OC_CAMPANHA(id_campanha) ON DELETE CASCADE
);
