DROP TABLE IF EXISTS planos_cobertura;
DROP TABLE IF EXISTS simulacoes;
DROP TABLE IF EXISTS campanha_regiao;
DROP TABLE IF EXISTS campanhas_transmissao;
DROP TABLE IF EXISTS regioes;
DROP TABLE IF EXISTS canais;
DROP TABLE IF EXISTS clientes;

CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    documento VARCHAR(30) UNIQUE,
    email VARCHAR(120) NOT NULL,
    telefone VARCHAR(30),
    segmento VARCHAR(80) NOT NULL,
    data_cadastro TIMESTAMP NOT NULL,
    ativo BOOLEAN NOT NULL
);

CREATE TABLE canais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    nome VARCHAR(120) NOT NULL,
    tipo_conteudo VARCHAR(80) NOT NULL,
    publico_alvo VARCHAR(120) NOT NULL,
    classificacao_indicativa VARCHAR(20),
    ativo BOOLEAN NOT NULL,
    CONSTRAINT fk_canais_clientes FOREIGN KEY (cliente_id) REFERENCES clientes(id)
);

CREATE TABLE regioes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    pais VARCHAR(80) NOT NULL,
    populacao_estimada INTEGER NOT NULL CHECK (populacao_estimada >= 0),
    indice_conectividade DECIMAL(5,2) NOT NULL CHECK (indice_conectividade BETWEEN 0 AND 100),
    latitude DECIMAL(10,6),
    longitude DECIMAL(10,6),
    area_km2 DECIMAL(12,2) NOT NULL CHECK (area_km2 > 0),
    prioridade_social INTEGER NOT NULL CHECK (prioridade_social BETWEEN 1 AND 5)
);

CREATE TABLE campanhas_transmissao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    canal_id BIGINT NOT NULL,
    nome VARCHAR(140) NOT NULL,
    descricao VARCHAR(500),
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    duracao_horas INTEGER NOT NULL CHECK (duracao_horas > 0),
    qualidade_desejada VARCHAR(20) NOT NULL CHECK (qualidade_desejada IN ('SD', 'HD', 'FULL_HD', '4K')),
    orcamento DECIMAL(14,2) NOT NULL CHECK (orcamento >= 0),
    status VARCHAR(30) NOT NULL CHECK (status IN ('PLANEJADA', 'EM_ANALISE', 'APROVADA', 'CANCELADA', 'FINALIZADA')),
    CONSTRAINT fk_campanhas_clientes FOREIGN KEY (cliente_id) REFERENCES clientes(id),
    CONSTRAINT fk_campanhas_canais FOREIGN KEY (canal_id) REFERENCES canais(id),
    CONSTRAINT ck_campanhas_periodo CHECK (data_inicio <= data_fim)
);

CREATE TABLE campanha_regiao (
    campanha_id BIGINT NOT NULL,
    regiao_id BIGINT NOT NULL,
    prioridade INTEGER NOT NULL CHECK (prioridade BETWEEN 1 AND 5),
    observacao VARCHAR(300),
    PRIMARY KEY (campanha_id, regiao_id),
    CONSTRAINT fk_cr_campanhas FOREIGN KEY (campanha_id) REFERENCES campanhas_transmissao(id) ON DELETE CASCADE,
    CONSTRAINT fk_cr_regioes FOREIGN KEY (regiao_id) REFERENCES regioes(id)
);

CREATE TABLE simulacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campanha_id BIGINT NOT NULL,
    custo_estimado DECIMAL(14,2) NOT NULL CHECK (custo_estimado >= 0),
    alcance_estimado INTEGER NOT NULL CHECK (alcance_estimado >= 0),
    qualidade_sinal DECIMAL(5,2) NOT NULL CHECK (qualidade_sinal BETWEEN 0 AND 100),
    viabilidade VARCHAR(20) NOT NULL CHECK (viabilidade IN ('BAIXA', 'MEDIA', 'ALTA')),
    recomendacao VARCHAR(600) NOT NULL,
    data_simulacao TIMESTAMP NOT NULL,
    CONSTRAINT fk_simulacoes_campanhas FOREIGN KEY (campanha_id) REFERENCES campanhas_transmissao(id) ON DELETE CASCADE
);

CREATE TABLE planos_cobertura (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campanha_id BIGINT NOT NULL,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    custo_total DECIMAL(14,2) NOT NULL CHECK (custo_total >= 0),
    alcance_total INTEGER NOT NULL CHECK (alcance_total >= 0),
    viabilidade_geral VARCHAR(20) NOT NULL CHECK (viabilidade_geral IN ('BAIXA', 'MEDIA', 'ALTA')),
    CONSTRAINT fk_planos_campanhas FOREIGN KEY (campanha_id) REFERENCES campanhas_transmissao(id) ON DELETE CASCADE
);
