CREATE TABLE T_OC_CLIENTE (
    id_cliente NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 7 INCREMENT BY 1) PRIMARY KEY,
    nome VARCHAR2(120) NOT NULL,
    documento VARCHAR2(30) UNIQUE,
    email VARCHAR2(120) NOT NULL,
    telefone VARCHAR2(30),
    segmento VARCHAR2(80) NOT NULL,
    data_cadastro TIMESTAMP NOT NULL,
    ativo NUMBER(1) NOT NULL CHECK (ativo IN (0, 1))
);

CREATE TABLE T_OC_CANAL (
    id_canal NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 8 INCREMENT BY 1) PRIMARY KEY,
    id_cliente NUMBER(19) NOT NULL,
    nome VARCHAR2(120) NOT NULL,
    tipo_conteudo VARCHAR2(80) NOT NULL,
    publico_alvo VARCHAR2(120) NOT NULL,
    classificacao_indicativa VARCHAR2(20),
    ativo NUMBER(1) NOT NULL CHECK (ativo IN (0, 1)),
    CONSTRAINT fk_canais_clientes FOREIGN KEY (id_cliente) REFERENCES T_OC_CLIENTE(id_cliente)
);

CREATE TABLE T_OC_REGIAO (
    id_regiao NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 19 INCREMENT BY 1) PRIMARY KEY,
    nome VARCHAR2(120) NOT NULL,
    estado VARCHAR2(2) NOT NULL,
    pais VARCHAR2(80) NOT NULL,
    populacao_estimada NUMBER(10) NOT NULL CHECK (populacao_estimada >= 0),
    indice_conectividade NUMBER(5,2) NOT NULL CHECK (indice_conectividade BETWEEN 0 AND 100),
    latitude NUMBER(10,6),
    longitude NUMBER(10,6),
    area_km2 NUMBER(12,2) NOT NULL CHECK (area_km2 > 0),
    prioridade_social NUMBER(1) NOT NULL CHECK (prioridade_social BETWEEN 1 AND 5)
);

CREATE TABLE T_OC_CAMPANHA (
    id_campanha NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 7 INCREMENT BY 1) PRIMARY KEY,
    id_cliente NUMBER(19) NOT NULL,
    id_canal NUMBER(19) NOT NULL,
    nome VARCHAR2(140) NOT NULL,
    descricao VARCHAR2(500),
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    duracao_horas NUMBER(10) NOT NULL CHECK (duracao_horas > 0),
    qualidade_desejada VARCHAR2(20) NOT NULL CHECK (qualidade_desejada IN ('SD', 'HD', 'FULL_HD', '4K')),
    orcamento NUMBER(14,2) NOT NULL CHECK (orcamento >= 0),
    status VARCHAR2(30) NOT NULL CHECK (status IN ('PLANEJADA', 'EM_ANALISE', 'APROVADA', 'CANCELADA', 'FINALIZADA')),
    CONSTRAINT fk_campanhas_clientes FOREIGN KEY (id_cliente) REFERENCES T_OC_CLIENTE(id_cliente),
    CONSTRAINT fk_campanhas_canais FOREIGN KEY (id_canal) REFERENCES T_OC_CANAL(id_canal),
    CONSTRAINT ck_campanhas_periodo CHECK (data_inicio <= data_fim)
);

CREATE TABLE T_OC_CAMPANHA_REGIAO (
    id_campanha NUMBER(19) NOT NULL,
    id_regiao NUMBER(19) NOT NULL,
    prioridade NUMBER(1) NOT NULL CHECK (prioridade BETWEEN 1 AND 5),
    observacao VARCHAR2(300),
    PRIMARY KEY (id_campanha, id_regiao),
    CONSTRAINT fk_cr_campanhas FOREIGN KEY (id_campanha) REFERENCES T_OC_CAMPANHA(id_campanha) ON DELETE CASCADE,
    CONSTRAINT fk_cr_regioes FOREIGN KEY (id_regiao) REFERENCES T_OC_REGIAO(id_regiao)
);

CREATE TABLE T_OC_SIMULACAO (
    id_simulacao NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 9 INCREMENT BY 1) PRIMARY KEY,
    id_campanha NUMBER(19) NOT NULL,
    custo_estimado NUMBER(14,2) NOT NULL CHECK (custo_estimado >= 0),
    alcance_estimado NUMBER(10) NOT NULL CHECK (alcance_estimado >= 0),
    qualidade_sinal NUMBER(5,2) NOT NULL CHECK (qualidade_sinal BETWEEN 0 AND 100),
    viabilidade VARCHAR2(20) NOT NULL CHECK (viabilidade IN ('BAIXA', 'MEDIA', 'ALTA')),
    recomendacao VARCHAR2(600) NOT NULL,
    data_simulacao TIMESTAMP NOT NULL,
    CONSTRAINT fk_simulacoes_campanhas FOREIGN KEY (id_campanha) REFERENCES T_OC_CAMPANHA(id_campanha) ON DELETE CASCADE
);

CREATE TABLE T_OC_PLANO_COBERTURA (
    id_plano NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (START WITH 5 INCREMENT BY 1) PRIMARY KEY,
    id_campanha NUMBER(19) NOT NULL,
    nome VARCHAR2(120) NOT NULL,
    descricao VARCHAR2(500),
    custo_total NUMBER(14,2) NOT NULL CHECK (custo_total >= 0),
    alcance_total NUMBER(10) NOT NULL CHECK (alcance_total >= 0),
    viabilidade_geral VARCHAR2(20) NOT NULL CHECK (viabilidade_geral IN ('BAIXA', 'MEDIA', 'ALTA')),
    CONSTRAINT fk_planos_campanhas FOREIGN KEY (id_campanha) REFERENCES T_OC_CAMPANHA(id_campanha) ON DELETE CASCADE
);
